///
/// @file    enzyme_pcivendor.h
/// @brief   Enzyme Hardware Abstraction Layer: PCI Vendor ID List
///
/// This data is partially derived from The PCI ID Repository,
/// located at http://pciids.sourceforge.net/
///
/// TODO:Precalculate hashes and generate this file from XML?
///
/// @author  Adam Leggett
///

// ---------------------------------------------------------------------------


namespace enzyme
{
    namespace pci
    {
        typedef struct
        {
            unsigned short id;
            const char* name;
        }
        VendorID;

        static VendorID gVendor[] =
        {
            { 0x0000, "Gammagraphx, Inc." },
            { 0x0010, "Allied Telesis" },
            { 0x001A, "Ascend Communications" },
            { 0x001C, "PEAK-System Technik GmbH" },
            { 0x0033, "Paradyne Corp." },
            { 0x003D, "Lockheed Martin-Marietta Corp." },
            { 0x0059, "Tiger Jet" },
            { 0x0070, "Hauppauge Computer Works" },
            { 0x0071, "Nebula Electronics Ltd." },
            { 0x0095, "Silicon Image" },
            { 0x00A7, "Teles AG" },
            { 0x00F5, "BFG Technologies" },
            { 0x0100, "Ncipher" },
            { 0x0123, "General Dynamics" },
            { 0x018A, "LevelOne" },
            { 0x021B, "Compaq" },
            { 0x0270, "Hauppauge Computer Works" },
            { 0x0291, "Davicom Semiconductor Inc." },
            { 0x02AC, "SpeedStream" },
            { 0x02E0, "XFX Pine Group Inc" },
            { 0x0303, "Hewlett-Packard" },
            { 0x0315, "SK-Electronics Co. Ltd." },
            { 0x0357, "TTTech AG" },
            { 0x036F, "Trigem Computer Inc." },
            { 0x0403, "Future Technology" },
            { 0x0432, "SCM Microsystems Inc." },
            { 0x045E, "Microsoft" },
            { 0x046D, "Logitech" },
            { 0x0482, "Kyocera" },
            { 0x04B3, "IBM" },
            { 0x04CF, "Myson Century Inc." },
            { 0x050D, "Belkin" },
            { 0x058F, "Alcor Micro Corporation" },
            { 0x05A9, "OmniVision" },
            { 0x05E3, "CyberDoor" },
            { 0x066F, "Sigmatel Inc." },
            { 0x0675, "Dynalink" },
            { 0x069D, "Hughes Network Systems" },
            { 0x0721, "Sapphire" },
            { 0x0795, "Wired Inc." },
            { 0x07CA, "AVerMedia" },
            { 0x07D0, "ITT Space Systems Division" },
            { 0x07E2, "ELMEG Communication Systems GmbH" },
            { 0x0842, "NPG, Personal Grand Technology" },
            { 0x08E6, "Gemalto NV" },
            { 0x08FF, "AuthenTec" },
            { 0x0925, "FIC" },
            { 0x093A, "PixArt Imaging Inc." },
            { 0x09C1, "Arris" },
            { 0x0A89, "BREA Technologies Inc" },
            { 0x0ACE, "ZyDAS Technology" },
            { 0x0B0B, "Rhino Equipment Corp." },
            { 0x0B3D, "Brontes Technologies" },
            { 0x0CCD, "TerraTec Electronic GmbH" },
            { 0x0E11, "Compaq" },
            { 0x0E21, "Cowon Systems" },
            { 0x0E55, "HaSoTec GmbH" },
            { 0x0EAC, "SHF Communication Technologies AG" },
            { 0x0F62, "Acrox Technologies Co. Ltd." },
            { 0x1000, "LSI" },
            { 0x1001, "Kolter Electronic" },
            { 0x1002, "ATI Technologies Inc." },
            { 0x1003, "ULSI Systems" },
            { 0x1004, "VLSI Technology" },
            { 0x1005, "Avance Logic" },
            { 0x1006, "Reply Group" },
            { 0x1007, "NetFrame Systems" },
            { 0x1008, "Epson" },
            { 0x100A, "Phoenix Technologies" },
            { 0x100B, "National Semiconductor" },
            { 0x100C, "Tseng Labs" },
            { 0x100D, "AST Research Inc" },
            { 0x100E, "Weitek" },
            { 0x1010, "Video Logic, Ltd." },
            { 0x1011, "Digital Equipment Corporation" },
            { 0x1012, "Micronics Computers Inc" },
            { 0x1013, "Cirrus Logic" },
            { 0x1014, "IBM" },
            { 0x1015, "LSI" },
            { 0x1016, "ICL Personal Systems" },
            { 0x1017, "SPEA Software AG" },
            { 0x1018, "Unisys Systems" },
            { 0x1019, "Elitegroup Computer Systems" },
            { 0x101A, "NCR" },
            { 0x101B, "Vitesse Semiconductor" },
            { 0x101C, "Western Digital" },
            { 0x101D, "Maxim Integrated Products" },
            { 0x101E, "American Megatrends Inc." },
            { 0x101F, "PictureTel" },
            { 0x1020, "Hitachi" },
            { 0x1021, "OKI" },
            { 0x1022, "AMD" },
            { 0x1023, "Trident Micro" },
            { 0x1024, "Zenith Data Systems" },
            { 0x1025, "Acer Incorporated [ALI]" },
            { 0x1028, "Dell" },
            { 0x1029, "Siemens" },
            { 0x102A, "LSI" },
            { 0x102B, "Matrox" },
            { 0x102C, "Chips and Technologies" },
            { 0x102D, "Wyse Technology Inc." },
            { 0x102E, "Olivetti Advanced Technology" },
            { 0x102F, "Toshiba America" },
            { 0x1030, "TMC Research" },
            { 0x1031, "Miro Computer Products AG" },
            { 0x1032, "Compaq" },
            { 0x1033, "NEC" },
            { 0x1034, "Framatome Connectors" },
            { 0x1035, "Comp. & Comm. Research Lab" },
            { 0x1036, "Future Domain" },
            { 0x1037, "Hitachi" },
            { 0x1038, "AMP Inc." },
            { 0x1039, "Silicon Integrated Systems [SiS]" },
            { 0x103A, "Seiko Epson Corporation" },
            { 0x103B, "Tatung" },
            { 0x103C, "Hewlett-Packard" },
            { 0x103E, "Solliday Engineering" },
            { 0x103F, "Synopsys/Logic Modeling Group" },
            { 0x1040, "Accelgraphics Inc." },
            { 0x1041, "Computrend" },
            { 0x1042, "Micron" },
            { 0x1043, "ASUSTeK" },
            { 0x1044, "Adaptec" },
            { 0x1045, "OPTi" },
            { 0x1046, "IPC Corporation" },
            { 0x1047, "Genoa Systems" },
            { 0x1048, "Elsa AG" },
            { 0x1049, "Fountain Technologies" },
            { 0x104A, "STMicroelectronics" },
            { 0x104B, "BusLogic" },
            { 0x104C, "Texas Instruments" },
            { 0x104D, "Sony Corporation" },
            { 0x104E, "Oak Technology" },
            { 0x104F, "Co-time Computer Ltd" },
            { 0x1050, "Winbond Electronics Corp" },
            { 0x1051, "Anigma" },
            { 0x1052, "Young Micro Systems" },
            { 0x1053, "Young Micro Systems" },
            { 0x1054, "Hitachi" },
            { 0x1055, "Efar Microsystems" },
            { 0x1056, "ICL" },
            { 0x1057, "Motorola" },
            { 0x1058, "Electronics & Telecommunications RSH" },
            { 0x1059, "Kontron" },
            { 0x105A, "Promise Technology" },
            { 0x105B, "Foxconn" },
            { 0x105C, "Wipro Infotech Limited" },
            { 0x105D, "Number 9" },
            { 0x105E, "Vtech" },
            { 0x105F, "Infotronic America Inc" },
            { 0x1060, "United Microelectronics [UMC]" },
            { 0x1061, "I.I.T." },
            { 0x1062, "Maspar Computer" },
            { 0x1063, "Ocean Office Automation" },
            { 0x1064, "Alcatel" },
            { 0x1065, "Texas Microsystems" },
            { 0x1066, "PicoPower Technology" },
            { 0x1067, "Mitsubishi" },
            { 0x1068, "Diversified Technology" },
            { 0x1069, "Mylex Corporation" },
            { 0x106A, "Aten Research Inc" },
            { 0x106B, "Apple Computer Inc." },
            { 0x106C, "Hynix Semiconductor" },
            { 0x106D, "Sequent Computer Systems" },
            { 0x106E, "DFI Inc." },
            { 0x106F, "City Gate Development Ltd" },
            { 0x1070, "Daewoo Telecom Ltd" },
            { 0x1071, "Mitac" },
            { 0x1072, "GIT Co Ltd" },
            { 0x1073, "Yamaha Corporation" },
            { 0x1074, "NexGen Microsystems" },
            { 0x1075, "Advanced Integrations Research" },
            { 0x1076, "Chaintech" },
            { 0x1077, "QLogic" },
            { 0x1078, "Cyrix" },
            { 0x1079, "I-Bus" },
            { 0x107A, "NetWorth" },
            { 0x107B, "Gateway 2000" },
            { 0x107C, "LG Electronics" },
            { 0x107D, "LeadTek" },
            { 0x107E, "Interphase" },
            { 0x107F, "Data Technology Corporation" },
            { 0x1080, "Contaq Microsystems" },
            { 0x1081, "Supermac Technology" },
            { 0x1082, "EFA Corporation of America" },
            { 0x1083, "Forex Computer Corporation" },
            { 0x1084, "Parador" },
            { 0x1085, "Tulip Computers" },
            { 0x1087, "Cache Computer" },
            { 0x1088, "Microcomputer Systems" },
            { 0x1089, "Data General" },
            { 0x108A, "Oakleigh Systems" },
            { 0x108D, "Olicom" },
            { 0x108E, "Sun Microsystems" },
            { 0x108F, "Systemsoft" },
            { 0x1090, "Compro" },
            { 0x1091, "Intergraph" },
            { 0x1092, "Diamond Multimedia" },
            { 0x1093, "National Instruments" },
            { 0x1094, "FIC" },
            { 0x1095, "Silicon Image" },
            { 0x1096, "Alacron" },
            { 0x1097, "Appian Technology" },
            { 0x1098, "Quantum Designs" },
            { 0x1099, "Samsung" },
            { 0x109A, "Packard Bell" },
            { 0x109B, "Gemlight Computer" },
            { 0x109C, "Megachips Corporation" },
            { 0x109D, "Zida Technologies" },
            { 0x109E, "Brooktree Corporation" },
            { 0x109F, "Trigem Computer" },
            { 0x10A0, "Meidensha Corporation" },
            { 0x10A1, "Juko Electronics" },
            { 0x10A2, "Quantum Corporation" },
            { 0x10A3, "Everex Systems Inc" },
            { 0x10A4, "Globe Manufacturing Sales" },
            { 0x10A5, "Smart Link" },
            { 0x10A6, "Informtech Industrial Ltd." },
            { 0x10A7, "Benchmarq Microelectronics" },
            { 0x10A8, "Sierra Semiconductor" },
            { 0x10A9, "Silicon Graphics" },
            { 0x10AA, "ACC Microelectronics" },
            { 0x10AB, "Digicom" },
            { 0x10AC, "Honeywell" },
            { 0x10AD, "Symphony Labs" },
            { 0x10AE, "Cornerstone Technology" },
            { 0x10AF, "Micro Computer Systems" },
            { 0x10B0, "CardExpert Technology" },
            { 0x10B1, "Cabletron Systems" },
            { 0x10B2, "Raytheon Company" },
            { 0x10B3, "Databook" },
            { 0x10B4, "STB Systems" },
            { 0x10B5, "PLX Technology" },
            { 0x10B6, "Madge Networks" },
            { 0x10B7, "3Com Corporation" },
            { 0x10B8, "SMC" },
            { 0x10B9, "ALi Corporation" },
            { 0x10BA, "Mitsubishi" },
            { 0x10BB, "Dapha Electronics Corporation" },
            { 0x10BC, "Advanced Logic Research" },
            { 0x10BD, "Surecom Technology" },
            { 0x10BE, "Tseng Labs" },
            { 0x10BF, "Most Inc." },
            { 0x10C0, "Boca Research" },
            { 0x10C1, "ICM Co. Ltd." },
            { 0x10C2, "Auspex Systems" },
            { 0x10C3, "Samsung" },
            { 0x10C4, "Award" },
            { 0x10C5, "Xerox Corporation" },
            { 0x10C6, "Rambus Inc." },
            { 0x10C7, "Media Vision" },
            { 0x10C8, "Neomagic Corporation" },
            { 0x10C9, "Dataexpert Corporation" },
            { 0x10CA, "Fujitsu" },
            { 0x10CB, "Omron Corporation" },
            { 0x10CC, "Mai Logic" },
            { 0x10CD, "Advanced System Products Inc." },
            { 0x10CE, "Radius" },
            { 0x10CF, "Fujitsu" },
            { 0x10D1, "FuturePlus" },
            { 0x10D2, "Molex" },
            { 0x10D3, "Jabil Circuit Inc." },
            { 0x10D4, "Hualon Microelectronics" },
            { 0x10D5, "Autologic" },
            { 0x10D6, "Cetia" },
            { 0x10D7, "BCM Advanced Research" },
            { 0x10D8, "Advanced Peripherals Labs" },
            { 0x10D9, "Macronix" },
            { 0x10DA, "Compaq" },
            { 0x10DB, "LSI" },
            { 0x10DC, "CERN/ECP/EDU" },
            { 0x10DD, "Evans & Sutherland" },
            { 0x10DE, "NVIDIA" },
            { 0x10DF, "Emulex Corporation" },
            { 0x10E0, "Integrated Micro Solutions" },
            { 0x10E1, "Tekram" },
            { 0x10E2, "Aptix Corporation" },
            { 0x10E3, "Tundra Semiconductor Corp." },
            { 0x10E4, "Tandem" },
            { 0x10E5, "Micro Industries Corporation" },
            { 0x10E6, "Gainbery Computer Products Inc." },
            { 0x10E7, "Vadem" },
            { 0x10E8, "Applied Micro Circuits Corp." },
            { 0x10E9, "Alps Electric" },
            { 0x10EA, "Intergraphics Systems" },
            { 0x10EB, "Artists Graphics" },
            { 0x10EC, "Realtek" },
            { 0x10ED, "Ascii" },
            { 0x10EE, "Xilinx" },
            { 0x10EF, "Racore" },
            { 0x10F0, "Peritek" },
            { 0x10F1, "Tyan" },
            { 0x10F2, "Achme Computer Inc." },
            { 0x10F3, "Alaris" },
            { 0x10F4, "S-MOS Systems Inc." },
            { 0x10F5, "NKK Corporation" },
            { 0x10F6, "Creative Electronic Systems SA" },
            { 0x10F7, "Matsushita" },
            { 0x10F8, "Altos India Ltd." },
            { 0x10F9, "PC Direct" },
            { 0x10FA, "Truevision" },
            { 0x10FB, "Thesys Gesellschaft fuer Mikroelektronik mbH" },
            { 0x10FC, "I-O Data Device Inc." },
            { 0x10FD, "Soyo Computer" },
            { 0x10FE, "Fast Multimedia AG" },
            { 0x10FF, "NCube" },
            { 0x1100, "Jazz Multimedia" },
            { 0x1101, "Initio Corporation" },
            { 0x1102, "Creative Labs" },
            { 0x1103, "HighPoint Technologies" },
            { 0x1104, "RasterOps" },
            { 0x1105, "Sigma" },
            { 0x1106, "VIA" },
            { 0x1107, "Stratus Computers" },
            { 0x1108, "Proteon" },
            { 0x1109, "Cogent Data Technologies" },
            { 0x110A, "Siemens" },
            { 0x110B, "Chromatic Research Inc." },
            { 0x110C, "Mini-Max Technology" },
            { 0x110D, "Znyx Advanced Systems" },
            { 0x110E, "CPU Technology" },
            { 0x110F, "Ross Technology" },
            { 0x1110, "Powerhouse Systems" },
            { 0x1111, "Santa Cruz Operation" },
            { 0x1112, "Osicom Technologies" },
            { 0x1113, "Accton Technology Corporation" },
            { 0x1114, "Atmel Corporation" },
            { 0x1115, "3D Labs" },
            { 0x1116, "Data Translation" },
            { 0x1117, "Datacube" },
            { 0x1118, "Berg Electronics" },
            { 0x1119, "ICP Vortex Computersysteme GmbH" },
            { 0x111A, "Efficient Networks" },
            { 0x111B, "Teledyne Electronic Systems" },
            { 0x111C, "Tricord Systems" },
            { 0x111D, "Integrated Device Technology" },
            { 0x111E, "Eldec" },
            { 0x111F, "Precision Digital Images" },
            { 0x1120, "EMC Corporation" },
            { 0x1121, "Zilog" },
            { 0x1122, "Multi-tech Systems" },
            { 0x1123, "Excellent Design Inc." },
            { 0x1124, "Leutron Vision" },
            { 0x1125, "Eurocore" },
            { 0x1126, "Vigra" },
            { 0x1127, "FORE Systems" },
            { 0x1129, "Firmworks" },
            { 0x112A, "Hermes Electronics" },
            { 0x112B, "Linotype-Hell AG" },
            { 0x112C, "Zenith Data Systems" },
            { 0x112D, "Ravicad" },
            { 0x112E, "Infomedia Microelectronics Inc." },
            { 0x112F, "Dalsa Inc." },
            { 0x1130, "Computervision" },
            { 0x1131, "Philips" },
            { 0x1132, "Mitel Corp." },
            { 0x1133, "Dialogic Corporation" },
            { 0x1134, "Mercury Computer Systems" },
            { 0x1135, "Xerox" },
            { 0x1136, "Momentum Data Systems" },
            { 0x1137, "Cisco Systems" },
            { 0x1138, "Ziatech Corporation" },
            { 0x1139, "Dynamic Pictures" },
            { 0x113A, "FWB Inc." },
            { 0x113B, "Network Computing Devices" },
            { 0x113C, "Cyclone Microsystems" },
            { 0x113D, "Leading Edge" },
            { 0x113E, "Sanyo" },
            { 0x113F, "Equinox Systems" },
            { 0x1140, "Intervoice" },
            { 0x1141, "Crest Microsystem" },
            { 0x1142, "Alliance Semiconductor Corporation" },
            { 0x1143, "NetPower" },
            { 0x1144, "Cincinnati Milacron" },
            { 0x1145, "Workbit Corporation" },
            { 0x1146, "Force Computers" },
            { 0x1147, "Interface Corp." },
            { 0x1148, "SysKonnect" },
            { 0x1149, "Win System Corporation" },
            { 0x114A, "VMIC" },
            { 0x114B, "Canopus" },
            { 0x114C, "Annabooks" },
            { 0x114D, "IC Corporation" },
            { 0x114E, "Nikon" },
            { 0x114F, "Digi International" },
            { 0x1150, "Thinking Machines" },
            { 0x1151, "JAE Electronics Inc." },
            { 0x1152, "Megatek" },
            { 0x1153, "Land Win" },
            { 0x1154, "Melco Inc." },
            { 0x1155, "Pine Technology" },
            { 0x1156, "Periscope Engineering" },
            { 0x1157, "Avsys Corporation" },
            { 0x1158, "Voarx" },
            { 0x1159, "Mutech" },
            { 0x115A, "Harlequin Ltd" },
            { 0x115B, "Parallax Graphics" },
            { 0x115C, "Photron Ltd." },
            { 0x115D, "Xircom" },
            { 0x115E, "Peer Protocols" },
            { 0x115F, "Maxtor" },
            { 0x1160, "Megasoft" },
            { 0x1161, "PFU Limited" },
            { 0x1162, "OA Laboratory Co Ltd" },
            { 0x1163, "Rendition" },
            { 0x1164, "Advanced Peripherals Technologies" },
            { 0x1165, "Imagraph Corporation" },
            { 0x1166, "Broadcom" },
            { 0x1167, "Mutoh Industries" },
            { 0x1168, "Thine Electronics" },
            { 0x1169, "Centre for Development of Advanced Computing" },
            { 0x116A, "Luminex Software" },
            { 0x116B, "Connectware" },
            { 0x116C, "Intelligent Resources Integrated Systems" },
            { 0x116D, "Martin-Marietta" },
            { 0x116E, "Electronics for Imaging" },
            { 0x116F, "Workstation Technology" },
            { 0x1170, "Inventec Corporation" },
            { 0x1171, "Loughborough Sound Images Plc" },
            { 0x1172, "Altera Corporation" },
            { 0x1173, "Adobe" },
            { 0x1174, "Bridgeport Machines" },
            { 0x1175, "Mitron Computer Inc." },
            { 0x1176, "SBE Incorporated" },
            { 0x1177, "Silicon Engineering" },
            { 0x1178, "Alfa Inc." },
            { 0x1179, "Toshiba" },
            { 0x117A, "A-Trend Technology" },
            { 0x117B, "LG Electronics" },
            { 0x117C, "Atto Technology" },
            { 0x117D, "Becton & Dickinson" },
            { 0x117E, "T/R Systems" },
            { 0x117F, "Integrated Circuit Systems" },
            { 0x1180, "Ricoh" },
            { 0x1181, "Telmatics International" },
            { 0x1183, "Fujikura Ltd" },
            { 0x1184, "Forks Inc" },
            { 0x1185, "Dataworld International Ltd" },
            { 0x1186, "D-Link" },
            { 0x1187, "Advanced Technology Laboratories" },
            { 0x1188, "Shima Seiki" },
            { 0x1189, "Matsushita" },
            { 0x118A, "Hilevel Technology" },
            { 0x118B, "Hypertec" },
            { 0x118C, "Corollary" },
            { 0x118D, "BitFlow" },
            { 0x118E, "Hermstedt GmbH" },
            { 0x119E, "Fujitsu" },
            { 0x11A9, "InnoSys" },
            { 0x11AA, "Actel" },
            { 0x11AB, "Marvell Technology" },
            { 0x11AC, "Canon" },
            { 0x11AD, "Lite-On" },
            { 0x11AE, "Aztech System Ltd" },
            { 0x11AF, "Avid Technology" },
            { 0x11B0, "V3 Semiconductor" },
            { 0x11B1, "Apricot Computers" },
            { 0x11B2, "Eastman Kodak" },
            { 0x11B3, "Barr Systems Inc." },
            { 0x11B4, "Leitch Technology" },
            { 0x11B5, "Radstone Technology" },
            { 0x11B6, "United Video Corp." },
            { 0x11B7, "Motorola" },
            { 0x11B8, "XPoint Technologies, Inc." },
            { 0x11B9, "Pathlight Technology" },
            { 0x11BA, "Videotron" },
            { 0x11BB, "Pyramid Technology" },
            { 0x11BC, "Network Peripherals" },
            { 0x11BD, "Pinnacle Systems" },
            { 0x11BE, "International Microcircuits" },
            { 0x11BF, "Astrodesign, Inc." },
            { 0x11C0, "Hewlett-Packard" },
            { 0x11C1, "LSI" },
            { 0x11C2, "Sand Microelectronics" },
            { 0x11C3, "NEC" },
            { 0x11C4, "Document Technologies, Inc." },
            { 0x11C5, "Shiva Corporation" },
            { 0x11C6, "Dainippon Screen Mfg. Co. Ltd." },
            { 0x11C7, "DCM Data Systems" },
            { 0x11C8, "Dolphin Interconnect Solutions AS" },
            { 0x11C9, "Magma" },
            { 0x11CA, "LSI" },
            { 0x11CB, "Specialix Research Ltd." },
            { 0x11CC, "Michels & Kleberhoff Computer GmbH" },
            { 0x11CD, "HAL Computer Systems, Inc." },
            { 0x11CE, "Netaccess" },
            { 0x11CF, "Pioneer Electronic Corporation" },
            { 0x11D0, "Lockheed Martin Federal Systems-Manassas" },
            { 0x11D1, "Auravision" },
            { 0x11D2, "Intercom Inc." },
            { 0x11D3, "Trancell Systems Inc." },
            { 0x11D4, "Analog Devices" },
            { 0x11D5, "Ikon Corporation" },
            { 0x11D6, "Tekelec Telecom" },
            { 0x11D7, "Trenton Technology, Inc." },
            { 0x11D8, "Image Technologies Development" },
            { 0x11D9, "TEC Corporation" },
            { 0x11DA, "Novell" },
            { 0x11DB, "Sega Enterprises" },
            { 0x11DC, "Questra Corporation" },
            { 0x11DD, "Crosfield Electronics Ltd." },
            { 0x11DE, "Zoran" },
            { 0x11DF, "New Wave PDG" },
            { 0x11E0, "Cray Communications A/S" },
            { 0x11E1, "GEC Plessey Semi Inc." },
            { 0x11E2, "Samsung" },
            { 0x11E3, "Quicklogic" },
            { 0x11E4, "Second Wave Inc." },
            { 0x11E5, "IIX Consulting" },
            { 0x11E6, "Mitsui-Zosen System Research" },
            { 0x11E7, "Toshiba" },
            { 0x121A, "3Dfx" },
            { 0x1274, "Ensoniq" },
            { 0x127A, "Rockwell International" },
            { 0x12B9, "3Com Corporation" },
            { 0x12D2, "NVIDIA" },
            { 0x12D8, "Pericom Semiconductor" },
            { 0x12EB, "Aureal Semiconductor" },
            { 0x131F, "Siig Inc" },
            { 0x1320, "Crypto AG" },
            { 0x1321, "Arcobel Graphics" },
            { 0x1322, "MTT" },
            { 0x1323, "Dome Inc" },
            { 0x1324, "Sphere Communications" },
            { 0x1325, "Salix Technologies" },
            { 0x1326, "Seachange International" },
            { 0x1327, "Voss Scientific" },
            { 0x1328, "Quadrant International" },
            { 0x1329, "Productivity Enhancement" },
            { 0x132A, "Microcom" },
            { 0x132B, "Broadband Technologies" },
            { 0x132C, "Micrel Inc" },
            { 0x132D, "Integrated Silicon Solution" },
            { 0x1330, "MMC Networks" },
            { 0x1331, "RadiSys Corporation" },
            { 0x1332, "Micro Memory" },
            { 0x1334, "Redcreek Communications" },
            { 0x1335, "Videomail" },
            { 0x1344, "Micron" },
            { 0x134A, "DTC" },
            { 0x1363, "Phoenix Technology" },
            { 0x1373, "Silicon Vision" },
            { 0x1374, "Silicom" },
            { 0x1376, "LMC" },
            { 0x1385, "Netgear" },
            { 0x1388, "Hitachi" },
            { 0x13A9, "Siemens" },
            { 0x13CA, "Iomega" },
            { 0x13F6, "C-Media" },
            { 0x13FE, "Advantech Co. Ltd" },
            { 0x1412, "VIA" },
            { 0x1414, "Microsoft" },
            { 0x1461, "Avermedia" },
            { 0x1462, "Micro-Star International" },
            { 0x14D2, "Titan Electronics" },
            { 0x14E4, "Broadcom" },
            { 0x14F1, "Conexant" },
            { 0x14F2, "Mobility Electronics" },
            { 0x14F3, "BroadLogic" },
            { 0x1502, "Mitsubishi" },
            { 0x1506, "Chameleon Systems" },
            { 0x151A, "Globetek" },
            { 0x151C, "Digital Audio Labs" },
            { 0x151D, "Fujitsu" },
            { 0x1524, "ENE Technology" },
            { 0x1532, "Echelon Corp." },
            { 0x153B, "TerraTec Electronic GmbH" },
            { 0x153F, "MIPS" },
            { 0x1540, "ProVideo" },
            { 0x156B, "2Wire" },
            { 0x1578, "HITT" },
            { 0x1589, "Leutron Vision" },
            { 0x1592, "Syba Tech" },
            { 0x15AD, "VMWare" },
            { 0x15B3, "Mellanox Technologies" },
            { 0x15B6, "Texas Memory Systems" },
            { 0x15BC, "Agilent Technologies" },
            { 0x15E8, "National Datacomm" },
            { 0x15E9, "Pacific Digital Corp." },
            { 0x1626, "TDK" },
            { 0x1631, "Packard Bell" },
            { 0x163C, "Smart Link" },
            { 0x166D, "Broadcom" },
            { 0x167B, "ZyDAS Technology" },
            { 0x1681, "Hercules" },
            { 0x168C, "Atheros" },
            { 0x1737, "Linksys" },
            { 0x173B, "Broadcom" },
            { 0x1799, "Belkin" },
            { 0x17AA, "Lenovo" },
            { 0x1814, "Ralink Technology" },
            { 0x182F, "Broadcom" },
            { 0x1854, "LG Electronics" },
            { 0x18AC, "DViCO" },
            { 0x18C8, "Cray" },
            { 0x18F7, "Commtech" },
            { 0x1969, "Atheros Communications" },
            { 0x19A2, "Emulex Corporation" },
            { 0x1AE0, "Google" },
            { 0x1AF4, "Red Hat" },
            { 0x1B4B, "Marvell Technology" },
            { 0x1DE1, "Tekram" },
            { 0x1FC1, "QLogic" },
            { 0x2000, "Smart Link" },
            { 0x2003, "Smart Link" },
            { 0x2004, "Smart Link" },
            { 0x2116, "ZyDAS Technology" },
            { 0x22B8, "Motorola" },
            { 0x2348, "Racore" },
            { 0x3388, "Hint Corp." },
            { 0x3D3D, "3DLabs" },
            { 0x4005, "Avance Logic" },
            { 0x4040, "NetXen Incorporated" },
            { 0x4444, "Internext Compression" },
            { 0x494F, "ACCES I/O" },
            { 0x5333, "S3" },
            { 0x6900, "Red Hat" },
            { 0x7063, "pcHDTV" },
            { 0x807D, "ASUSTeK" },
            { 0x8086, "Intel Corporation" },
            { 0x80EE, "InnoTek Systemberatung GmbH" },
            { 0x8322, "Sodick America Corp." },
            { 0x8384, "SigmaTel" },
            { 0x8401, "TRENDware" },
            { 0x8686, "ScaleMP" },
            { 0x8800, "Trigem Computer" },
            { 0x8866, "T-Square Design" },
            { 0x8888, "Silicon Magic" },
            { 0x8912, "TRX" },
            { 0x8C4A, "Winbond" },
            { 0x8E0E, "Computone Corporation" },
            { 0x8E2E, "KTI" },
            { 0x9004, "Adaptec" },
            { 0x9005, "Adaptec" },
            { 0x907F, "Atronics" },
            { 0x919A, "Gigapixel" },
            { 0x9412, "Holtek" },
            { 0x9699, "Omni Media Technology" },
            { 0x9710, "NetMos Technology" },
            { 0x9902, "Stargen" },
            { 0xA0A0, "AOPEN" },
            { 0xA0F1, "UNISYS" },
            { 0xA200, "NEC" },
            { 0xA259, "Hewlett-Packard" },
            { 0xA25B, "Hewlett-Packard" },
            { 0xA304, "Sony" },
            { 0xA727, "3Com Corporation" },
            { 0xAA42, "Scitex" },
            { 0xAA55, "Ncomputing" },
            { 0xAAAA, "Adnaco Technology" },
            { 0xABCD, "Vadatech" },
            { 0xAC1E, "Digital Receiver Technology Inc" },
            { 0xAC3D, "Actuality Systems" },
            { 0xAD00, "Alta Data Technologies LLC" },
            { 0xAECB, "Adrienne Electronics Corporation" },
            { 0xAFFE, "Sirrix AG" },
            { 0xB10B, "Uakron PCI Project" },
            { 0xB1B3, "Shiva Europe Limited" },
            { 0xBD11, "Pinnacle Systems" },
            { 0xBDBD, "Blackmagic Design" },
            { 0xC001, "TSI Telsys" },
            { 0xC0A9, "Micron/Crucial Technology" },
            { 0xC0DE, "Motorola" },
            { 0xC0FE, "Motion Engineering" },
            { 0xCA50, "Varian Australia Pty Ltd" },
            { 0xCACE, "CACE Technologies" },
            { 0xCAFE, "Chrysalis-ITS" },
            { 0xCCCC, "Catapult Communications" },
            { 0xCCEC, "Curtiss-Wright Controls Embedded Computing" },
            { 0xCDDD, "Tyzx" },
            { 0xCEBA, "KEBA AG" },
            { 0xD161, "Digium" },
            { 0xD4D4, "Dy4 Systems" },
            { 0xD531, "I+ME ACTIA GmbH" },
            { 0xD84D, "Exsys" },
            { 0xDB10, "Diablo Technologies" },
            { 0xDEAD, "Indigita" },
            { 0xDEAF, "Middle Digital" },
            { 0xDEDA, "SoftHard Technology" },
            { 0xE000, "Winbond" },
            { 0xE159, "Tiger Jet" },
            { 0xE4BF, "EKF Elektronik GmbH" },
            { 0xE55E, "Essence Technology" },
            { 0xEA01, "Eagle Technology" },
            { 0xEA60, "RME" },
            { 0xEABB, "Aashima Technology" },
            { 0xEACE, "Endace Measurement Systems" },
            { 0xEC80, "Belkin" },
            { 0xECC0, "Echo Digital Audio" },
            { 0xEDD8, "ARK Logic" },
            { 0xF043, "ASUSTeK" },
            { 0xF05B, "Foxconn" },
            { 0xF1D0, "AJA Video" },
            { 0xF5F5, "F5 Networks" },
            { 0xF849, "ASRock Incorporation" },
            { 0xFA57, "Interagon" },
            { 0xFAB7, "Fabric7 Systems" },
            { 0xFEBD, "Ultraview" },
            { 0xFEDA, "Broadcom" },
            { 0xFEDE, "Fedetec" },
            { 0xFFFD, "XenSource" },
            { 0xFFFE, "VMWare" },
        };
    };
};
